name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradly
      run: ./gradlew wrapper --gradle-version 7.3.3 --distribution-type all
     # run: ./gradlew build 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      # run: ./gradlew build
      run: ./gradlew assembleRelease


    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v2
      with:
        name: scene-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
